<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-07-11T18:12:38 IST" name="Suite" finished-at="2024-07-11T18:13:17 IST" duration-ms="39384">
    <groups>
    </groups>
    <test started-at="2024-07-11T18:12:38 IST" name="Test" finished-at="2024-07-11T18:13:17 IST" duration-ms="39384">
      <class name="TestLayer.HomepageTest">
        <test-method signature="validateUserOnHomePage()[pri:1, instance:TestLayer.HomepageTest@50b5ac82]" started-at="2024-07-11T18:13:10 IST" name="validateUserOnHomePage" finished-at="2024-07-11T18:13:13 IST" duration-ms="2893" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateUserOnHomePage -->
        <test-method signature="validateTitle()[pri:2, instance:TestLayer.HomepageTest@50b5ac82]" started-at="2024-07-11T18:13:13 IST" name="validateTitle" finished-at="2024-07-11T18:13:13 IST" duration-ms="9" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTitle -->
        <test-method signature="validateUrl()[pri:3, instance:TestLayer.HomepageTest@50b5ac82]" started-at="2024-07-11T18:13:13 IST" name="validateUrl" finished-at="2024-07-11T18:13:13 IST" duration-ms="9" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateUrl -->
        <test-method signature="validateLogo()[pri:4, instance:TestLayer.HomepageTest@50b5ac82]" started-at="2024-07-11T18:13:13 IST" name="validateLogo" finished-at="2024-07-11T18:13:17 IST" duration-ms="4565" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at TestLayer.HomepageTest.validateLogo(HomepageTest.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLogo -->
      </class> <!-- TestLayer.HomepageTest -->
      <class name="TestLayer.LoginTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:TestLayer.LoginTest@446293d]" started-at="2024-07-11T18:12:38 IST" name="setUp" finished-at="2024-07-11T18:13:05 IST" duration-ms="26762" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="validateLoginFunctionality()[pri:1, instance:TestLayer.LoginTest@446293d]" started-at="2024-07-11T18:13:05 IST" name="validateLoginFunctionality" finished-at="2024-07-11T18:13:10 IST" duration-ms="5092" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLoginFunctionality -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:TestLayer.LoginTest@446293d]" started-at="2024-07-11T18:13:17 IST" name="tearDown" finished-at="2024-07-11T18:13:17 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- TestLayer.LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
